# Etapa 1: Builder (solo para compilar)
FROM python:3.11-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 2: Imagen final (ligera)
FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY app.py .

RUN adduser -D appuser && chown -R appuser /app
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]
